Book/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :notes do
		resources :reviews
	end
	root 'notes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Book/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Book/app/models/category.rb
class Category < ApplicationRecord
	has_many :notes
end

Book/app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :reviews
	has_attached_file :note_img, :styles => { :note_index =>"250x350>", :note_show => "325x475>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :note_img, :content_type => /\Aimage\/.*\z/
end

Book/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :note
	belongs_to :user

end

Book/app/models/user.rb
class User < ApplicationRecord
	has_many :notes
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Book/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

Book/app/controllers/notes_controller.rb
class NotesController < ApplicationController
	before_action :find_note, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    
	
	def index
	  if params[:category].blank?
		@notes = Note.all.order("created_at DESC")
	  else
		@category_id = Category.find_by(name: params[:category]).id
		  
		@notes = Note.where(:category_id => @category_id).order("created_at DESC")
	  end
	end

	def show

	end

	def new
		@note = current_user.notes.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@note = current_user.notes.build(note_params)
		@note.category_id = params[:category_id]

		if @note.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@note.category_id = params[:category_id]

		if @note.update(note_params)
			redirect_to note_path(@note)
		else
			render 'edit'
	
		end
	end

	def destroy
		@note.destroy
		redirect_to root_path
	end

	private

	 def note_params
	 	params.require(:note ).permit(:title, :description, :author, :category_id, :note_img)
	 end

	 def find_note
	 	@note = Note.find(params[:id])
	 end

end

Book/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_note
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.note_id = @note.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to note_path(@note)
		else
			render 'new'
		end
	end
	def edit
	end
	def update
	
		if @review.update(review_params)
			redirect_to note_path(@note)
		else 
		    render 'edit'
		end
	end
	def destroy
		@review.destroy
		redirect_to note_path(@note)
	end

	private

	  def review_params
	  	params.require(:review).permit(:rating, :comment)
	  end

	  def find_note
	  	@note = Note.find(params[:note_id])
	  end
	  def find_review
	  	@review = Review.find(params[:id])
	  end

end

Book/app/helpers/application_helper.rb
module ApplicationHelper
end

Book/app/helpers/notes_helper.rb
module NotesHelper
end

Book/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
        
         <%= link_to "Book Review", root_path, class: "navbar-brand" %>
        
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>"5>
                  <%= link_to category.name, notes_path(category: category.name), class: "link" %>
              </li>
                  
              <% end %>

            </ul>
          </li>
          <% if user_signed_in? %>

            <li><%= link_to "Add Book" , new_note_path %></li>
          <% end %>
        </ul>

      </div>
    </nav>
    

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

Book/app/views/notes/_form.html.erb
<%= simple_form_for @note, :html => { :multipart => true} do |f| %> 
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a
   category") %>
  <%= f.file_field :note_img %>
  <%= f.input :title, lable: "Note Title" %>
  <%= f.input :description %>
  <%=f.input :author %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>

Book/app/views/notes/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-note-form">


    <h1>Edit Book</h1>
    <%= simple_form_for @note, :html => { :multipart => true} do |f| %>
      <%= f.select :category_id, @categories %>
      <%= f.file_field :note_img %>
      <%= f.input :title, lable: "Note Title" %>
      <%= f.input :description %>
      <%=f.input :author %>
      <%= f.button :submit %>
    <% end %>
  </div>

</div>

Book/app/views/notes/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @notes.count == 0 %>

  <h1>There are no books currently in this category</h1>

<% else %>

  <div class="row">

    <% @notes.each do |note| %>

      <div class="col-md-3">
        <a href="/notes/<%= note.id %>">
  	      <%= image_tag note.note_img.url(:note_index), class:"book" %>
        </a>
       </div>
    <% end %>
  </div>
<% end %>

Book/app/views/notes/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-note-form">
    <h1>New Book</h1>
    <%=render 'form' %>
  </div>
</div>

Book/app/views/notes/show.html.erb
<div class="row">
  <div class="col-md-4">
      <%= image_tag @note.note_img.url(:note_show), class: "note_show" %>
  </div>
  <div clas="col-md-8">
  	<div class="note-info">
    <h2 class="note-title"><%= @note.title %></h2>
    <h3 class="note-author"><span>From</span> <%= @note.author %></h3>
    <h2 class="avg-rating">Average Rating</h2>
    <div class="average-review-rating" data-score=<%= @average_review %>></div>
    <span class="number-of-reviews">Based on <%= @note.reviews.count %> reviews</span>
    <p class="note-desc"><%= @note.description %></p>
  </div>
</div>

<div class="row">
	<div class="col-md-4">
	  <div class="reviews">
		  <!-- Where the reviews/rating will go -->
		  <h1>Reviews</h1>
		  <%= render @note.reviews %>
		  <div>
		    <%= link_to "Add Review", new_note_review_path(@note), class: "btn-custom" %>
		  </div>

	   </div>
	</div>

</div>
<div class="links btn-group">


  <%= link_to "Back", root_path, class: "btn btn-custom" %>

  <% if user_signed_in? %>
    <% if @note.user_id == current_user.id %>


  

      <%= link_to "Edit", edit_note_path(@note), class: "btn btn-custom" %>
      <%= link_to "Delete", note_path(@note), method:  :delete, data: {confirm: "Are you sure?" } %>
    <% end %>
  <% end %>
</div>

<script>
  $('.review-rating').raty({
	readOnly: true,
	path: '/assets'
	score: function() {
	  return $(this).attr('data-score');
	},
	
  });
</script>
<script>
  $('.average-review-rating').raty({
	readOnly: true,
	path: '/assets',
	score: function() {
	  return $(this).attr('data-score')
	},
		
  });

</script>

Book/app/views/reviews/_form.html.erb
<%= simple_form_for([@note, @note.reviews.build]) do |f| %>
  <div id="rating-form">
     <%= f.input :rating %>
   	
  </div>
  
  <%= f.input :comment %>
  <%= f.button :submit, :class => "btn-custom2" %>
<% end %>
<script>
  $('.review-rating').raty({
	path: '/assets/'
	scoreName: 'review[rating]'
	
  });
</script>

Book/app/views/reviews/_review.html.erb
<div class="review">

 <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>


  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div class="links btn-group">
    

        <%= link_to "Edit", edit_note_review_path(review.note, review), class: "btn btn-custom"  %>
        <%= link_to "Delete", note_review_path(review.note, review), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-custom" %>
       </div>
    <% end %>
  <% end %>
</div>

Book/app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="edit-note-form">


    <h1>Edit Review</h1>

    <%= simple_form_for([@note, @review]) do |f| %>
      <div id="rating-form">
   	    <%= f.input :rating %>
   	
   	  </div>
   	  
      <%= f.input :comment %>
      <%= f.button :submit, :class => "btn-custom2" %>
    <% end %>
  </div>
</div>
<script>
  $('.review-rating').raty({
	path: '/assets/'
	scoreName: 'review[rating]'
	
  });
</script>

Book/app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="new-note-form">



    <h1>New Review</h1>

    <%= render 'form' %>
  </div>
</div>  
   